### ISSUE TITLE
ReferrerFilter must not be edited directly

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-service.en#198]
Issue in ./help/headless/deployment/referrer-filter.md

According to [1] one can add new hostnames to the ReferrerFilter by providing an according OSGi config as:

**org.apache.sling.security.impl.ReferrerFilter.cfg.json**

I don’t think this is 100% correct, though as this could overwrite the configuration provided by engineering as can be seen in the 

Developer console:

```
- pid: "org.apache.sling.security.impl.ReferrerFilter"
  properties:
    allow.hosts.regexp:
    - "https://.*\\.adobe\\.com:443"
    - "https://.*\\.adobe\\.net:443"
    - "https://.*\\.workfront\\.com:443"
    - "https://.*\\.workfront-dev\\.com:443"
    - "https://.*\\.dev\\.workfront\\.tech:443"
- pid: "org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl"
```

So.. something else would probably stop working.

I *believe* the better approach is to provide an amendment config.. In general this seems to always be the better idea. Please x-check with engineering and don't take my word for it. I am following my intuition, only. 

[1] https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/headless/deployment/referrer-filter
